---
Simulation:
  MaxCycles: 100
  EnergyPerCycle: 10
Environment:
  Width: 10
  Height: 10
  Torus: True
Dooder:
  StartingEnergySupply: 5
  StartingAgentCount: 10
  Moore: True
Energy:
  MaxEnergyLife: 10
  MinEnergyLife: 2
Information:
  Collectors: [DooderCount, EnergyCount, DirectionCount]
  Granularity: 2
