---
Simulation:
  MaxCycles: 100
  EnergyPerCycle: 10
Environment:
  Width: 10
  Height: 10
  Torus: True
Dooder:
  StartingEnergySupply: 5
  StartingAgentCount: 10
  Moore: True
Energy:
  MaxEnergyLife: 10
  MinEnergyLife: 2
Information:
  Collectors: [DooderCount, EnergyCount, DirectionCount]
  Granularity: 2
Strategies:
  Lifespan: [Uniform, { "min": 1, "max": 10 }]
  EnergyPerCycle: [Fixed, { "value": 10 }]
  MaxTotalEnergy: [Normal, { "mean": 50, "deviation": 10 }]
  Placement: RandomLocation
